/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appPatientsLayoutRouteImport } from './routes/(app)/patients/_layout'
import { Route as appPatientsIndexRouteImport } from './routes/(app)/patients/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appPatientsLayoutRoute = appPatientsLayoutRouteImport.update({
  id: '/(app)/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const appPatientsIndexRoute = appPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appPatientsLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patients': typeof appPatientsLayoutRouteWithChildren
  '/patients/': typeof appPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patients': typeof appPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/patients': typeof appPatientsLayoutRouteWithChildren
  '/(app)/patients/': typeof appPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patients' | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patients'
  id: '__root__' | '/' | '/(app)/patients' | '/(app)/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appPatientsLayoutRoute: typeof appPatientsLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/patients': {
      id: '/(app)/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof appPatientsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/patients/': {
      id: '/(app)/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof appPatientsIndexRouteImport
      parentRoute: typeof appPatientsLayoutRoute
    }
  }
}

interface appPatientsLayoutRouteChildren {
  appPatientsIndexRoute: typeof appPatientsIndexRoute
}

const appPatientsLayoutRouteChildren: appPatientsLayoutRouteChildren = {
  appPatientsIndexRoute: appPatientsIndexRoute,
}

const appPatientsLayoutRouteWithChildren =
  appPatientsLayoutRoute._addFileChildren(appPatientsLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appPatientsLayoutRoute: appPatientsLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
